### ISSUE TITLE
Please, add default user\pass in README

### ISSUE THREAD

**Issue by redteam88** [bettercap/ui#10]
Please, add default user\pass in README ;-)

**Comment by evilsocket** [comment]
Please read the doc https://www.bettercap.org/usage/#web-ui, it clearly says where to find those credentials and, most importantly, that you are supposed to change them ... i assume you did neither.

**Comment by philprobinson84** [comment]
Based on the Installation page of your website it is likely to expect most users will choose the Docker route, and I presume this is your recommended option as you list it first.

In this scenario, reading the defaults out of /usr/local/share/bettercap/caplets/http-ui.cap on the docker container is not trivial, so I would suggest reconsidering @redteam88's request.

Alternatively you could consider updating your usage documentation (clearly not written with the Docker install option in mind) to match your installation documentation (Docker first).

**Comment by yungtravla** [comment]
The request was to include the default username and password in the documentation, while the documentation clearly points out in a big red warning that you should change the default credentials, and where to change them.

**Comment by nazariyv** [comment]
I came across the same issue, no idea where to get the credentials. I went the Docker route

**Comment by jaykumar2001** [comment]
You can run shell command using `!` as escape. View content of the file

` ! cat /usr/local/share/bettercap/caplets/https-ui.cap`

**Comment by JDarzan** [comment]
documentation is for Docker, for repo "/usr/local/share/bettercap/caplets/https-ui.cap" dont exist! oO

**Comment by evilsocket** [comment]
@JDarzan no the doc is not for docker https://www.bettercap.org/usage/

![Schermata 2021-03-15 alle 10 45 49](https://user-images.githubusercontent.com/86922/111134168-a293d100-857b-11eb-916c-3682f9655c90.png)

**Comment by softspork** [comment]
after `docker run -it --privileged --net=host bettercap/bettercap` I've had to run `! cat http-ui.cap`

**Comment by hwac121** [comment]
Rather than give people a hard time and be a jerk just give him the freaking credentials:
login: user
password: pass

**Comment by evilsocket** [comment]
@hwac121 what about go fuck yourself, uh?
