### ISSUE TITLE
Install Option Removed from Makefile

### ISSUE THREAD

**Issue by ttepatti** [bettercap/ui#104]
Hello,

I believe the "install" option has been removed from the project's Makefile, making the project impossible to install when following the steps outlined in the README file:

```
git clone https://github.com/bettercap/ui.git ~/ui
cd ~/ui
make deps
make build
sudo make install
```

On the final step, you'll receive:

```make: *** No rule to make target 'install'. Stop.```

I believe this is due to a change that happened in the Makefile 3 weeks ago, in the following commit: https://github.com/bettercap/ui/commit/18178a795671599b0f2f2a249eab362a8a363363

It looks like the install section of the Makefile was removed, specifically:

```
install: build
	@echo "installing to /usr/local/share/bettercap/ui ..."
	@cp -rf dist/ui /usr/local/share/bettercap/ui
```

I'm not sure if the Makefile needs to be updated, or the README instructions 😅 But either way, I wanted to bring this to your attention.

Thanks!

**Comment by Benzo-Fury** [comment]
Im getting this error to, any fix?
