### ISSUE TITLE
No rule to make target 'deps'.  Stop. make: ng: Command not found make: *** [Makefile:7: build] Error 127 cp: cannot stat 'dist/ui': No such file or directory make: *** [Makefile:16: install] Error 1

### ISSUE THREAD

**Issue by N2Network** [bettercap/ui#11]
Can someone help me out with these errors? I can these commands first.

> curl -sL https://deb.nodesource.com/setup_11.x | bash -
> apt-get install -y nodejs
> sudo apt-get install build-essential curl git m4 ruby texinfo libbz2-dev libcurl4-openssl-dev libexpat-dev libncurses-dev zlib1g-dev
> apt-get install 

npm

Linux kali-pi 4.14.93-Re4son-v7+ #1 SMP Thu Jan 24 12:44:19 AEDT 2019 armv7l GNU/Linux

> git clone https://github.com/bettercap/ui.git ~/ui
> Cloning into '/root/ui'...
> remote: Enumerating objects: 227, done.
> remote: Counting objects: 100% (227/227), done.
> remote: Compressing objects: 100% (171/171), done.
> remote: Total 4087 (delta 151), reused 114 (delta 55), pack-reused 3860
> Receiving objects: 100% (4087/4087), 10.51 MiB | 3.46 MiB/s, done.
> Resolving deltas: 100% (1800/1800), done.
> Checking out files: 100% (1722/1722), done.
> root@kali-pi:~# cd ~/ui
> root@kali-pi:~/ui# make deps
> make: *** No rule to make target 'deps'.  Stop.
> root@kali-pi:~/ui# make build
> buiding ui ...
> make: ng: Command not found
> make: *** [Makefile:7: build] Error 127
> root@kali-pi:~/ui# sudo make install
> installing to /usr/local/share/bettercap/ui ...
> cp: cannot stat 'dist/ui': No such file or directory
> make: *** [Makefile:16: install] Error 1
> root@kali-pi:~/ui#

**Comment by evilsocket** [comment]
`ng Command not found` ... this is a problem with your nodejs and angular installation, not of the UI.

**Comment by N2Network** [comment]
> installation

Thanks, I don't have a lot of experience with this. Can you point me in the right direction on how I can resolve?

**Comment by evilsocket** [comment]
why don't you just use the precompiled release instead? https://www.bettercap.org/usage/#web-ui

in case you desperately need to compile this yourself, i can point you to http://bfy.tw/MzrB

**Comment by N2Network** [comment]
> why don't you just use the precompiled release instead? https://www.bettercap.org/usage/#web-ui
> 
> in case you desperately need to compile this yourself, I can point you to http://bfy.tw/MzrB

I definitely don't need to compile myself I was just going through the instructions. I'll read through the link you sent. Thank you.

**Comment by N2Network** [comment]
I actually think I already have it configured based on that link you sent. I think my issue is the server is setting the IP address of 127.0.0.1. I thought I could fix this buy using "set http.server.address" and configuring it to the local ip address of wlan0. However, when I do this I can't open a web browser from another computer on the network. As I think about this more however, I think I'm mixing two different functions. How can I enable the web-ui and access it from another computer on the lan? I'm running ona  raspberry pi so hitting a web interface on it is not ideal.

**Comment by evilsocket** [comment]
RTFM
