### ISSUE TITLE
en0 interface on Mac not show for wifi module select

### ISSUE THREAD

**Issue by sidelux** [bettercap/ui#12]
Hi,

i noticed that from Mac in the select field en0 interface is not showed:

![image](https://user-images.githubusercontent.com/18572941/55320261-f7191100-5476-11e9-9ce6-80467a9c0c1b.png)

The only way to start with this interface is manually send `wifi.recon on` command.
Is a problem or i missed something?

Thanks!

**Comment by evilsocket** [comment]
is it disconnected from your home network? you can only use interfaces that have no address and are disconnected

**Comment by sidelux** [comment]
Uhm i didn't know that, maybe can be useful show all interfaces and a warning where one selected is "busy".
Thanks, anyway
