### ISSUE TITLE
npm audit fix is creating deps 

### ISSUE THREAD

**Issue by marxenegls** [bettercap/ui#20]
$ make deps
installing dependencies ...

> node-sass@4.12.0 install /home/ma/ui/node_modules/node-sass
> node scripts/install.js

Cached binary found at /home/ma/.npm/node-sass/4.12.0/linux-x64-64_binding.node

> node-sass@4.12.0 postinstall /home/marui/node_modules/node-sass
> node scripts/build.js

Binary found at /home/ma/ui/node_modules/node-sass/vendor/linux-x64-64/binding.node
Testing binary
Binary is fine

> electron@4.1.1 postinstall /home/ma/ui/node_modules/electron
> node install.js

npm WARN The package tar is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/@angular/compiler-cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1190 packages from 1371 contributors and audited 43175 packages in 105.833s
found 596 vulnerabilities (1 moderate, 595 high)
  run `npm audit fix` to fix them, or `npm audit` for details

ma@os:~/ui$ npm audit fix
npm WARN @angular/animations@7.2.9 requires a peer of @angular/core@7.2.9 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/compiler-cli@7.2.8 requires a peer of @angular/compiler@7.2.8 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.3.1 requires a peer of popper.js@^1.14.7 but none is installed. You must install peer dependencies yourself.
npm WARN The package tar is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/@angular/compiler-cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ bootstrap@4.3.1
removed 2 packages and updated 6 packages in 36.528s
fixed 596 of 596 vulnerabilities in 43175 scanned packages

**Comment by marxenegls** [comment]
i noticed i'm gonna have to upgrade the pkg version from 1.6 to latest .
I presume i should uninstall first . I'm not sure about those vulns though if they're intentional or not  it is an mitm afterall not to mention yous would'av noticed em too , right ??

**Comment by marxenegls** [comment]
i managed .. via caplets

**Comment by cyrus104** [comment]
@marxenegls, I'm running into a similar issue. What did you mean when use said via caplets?

Thanks
