### ISSUE TITLE
UI Authentication Failure

### ISSUE THREAD

**Issue by hard-coded** [bettercap/ui#23]
After starting the UI with `sudo bettercap -caplet https-ui`, I attempted to login using the default credentials `pwnagotchi:pwnagotchi`. The UI returns `401 OK: wrong credentials` and the following error is logged: `[20:11:46] [sys.log] [war] api.rest Unauthorized authentication attempt from 10.0.0.1:56223 to /api/session?from=`

**Comment by buffermet** [comment]
Yes because those are clearly not the default credentials for **bettercap**'s web ui...

https://github.com/bettercap/caplets/blob/9b568997eee61f246286718b80e3ad16c3bcf422/https-ui.cap#L16

**Comment by buffermet** [comment]
The default credentials are in the `https-ui.cap` file that you're using, you must change them.

**Comment by ConsultanIT** [comment]
@buffermet 

hi Bro i need your help for this issue !! 
**bettercap v2.23 (built for linux amd64 with go1.11.6)**

![image](https://user-images.githubusercontent.com/34819160/94926447-bb6e6580-04b8-11eb-82c5-d4d104e255fe.png)
![image](https://user-images.githubusercontent.com/34819160/94926491-cde89f00-04b8-11eb-9017-8f45c2e73bf9.png)
![image](https://user-images.githubusercontent.com/34819160/94926573-e953aa00-04b8-11eb-8360-f3f694bfb20c.png)
![image](https://user-images.githubusercontent.com/34819160/94926663-038d8800-04b9-11eb-9107-476d92b821e9.png)

best regards

**Comment by buffermet** [comment]
@ConsultanIT 

Your screenshot shows the issue clearly printed in a red message:

<img width="391" alt="Screen Shot 2020-10-03 at 9 57 41 pm" src="https://user-images.githubusercontent.com/29265684/94991025-974b7b00-05c3-11eb-8f50-3f985a308e10.png">

Stop commenting on unrelated issues.
