### ISSUE TITLE
Error: EACCES: permission denied, mkdir '/usr/share/bettercap/ui/node_modules/electron/.electron'

### ISSUE THREAD

**Issue by satyendra22** [bettercap/ui#31]
Getting permission error while running below command. same error occurred even for sudo user 

kali@kali:/usr/share/bettercap/ui$ sudo make deps

installing dependencies ...

> electron@4.1.1 postinstall /usr/share/bettercap/ui/node_modules/electron
> node install.js

/usr/share/bettercap/ui/node_modules/electron/install.js:49
  throw err
  ^

Error: EACCES: permission denied, mkdir '/usr/share/bettercap/ui/node_modules/electron/.electron'
npm WARN @angular/animations@7.2.9 requires a peer of @angular/core@7.2.9 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/compiler-cli@7.2.8 requires a peer of @angular/compiler@7.2.8 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.2.1 requires a peer of popper.js@^1.14.6 but none is installed. You must install peer dependencies yourself.
npm WARN The package tar is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/@angular/compiler-cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@4.1.1 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@4.1.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by evilsocket** [comment]
not sure what you're trying to do, in order to install the ui you can just run "ui.update" from bettercap then restart and run one of the http-ui or https-ui caplets
