### ISSUE TITLE
A module to manage bettercap's UI. Disabled in Kali: use apt install bettercap-ui to install and/or update ui.

### ISSUE THREAD

**Issue by Hossein228** [bettercap/ui#35]
![Screenshot_2020-07-28_11-40-43](https://user-images.githubusercontent.com/65797544/88692735-aa4d5500-d113-11ea-8841-58879c9393ca.png)

when i open the ui help menu by typing help ui it gives me an error saying that bettercap-ui has been disabled in kali, try installing it or updating it as shown in figure. I have tirelessly searched google and other forums but none was related this issue. Please guide me for the solution.

**Comment by ConsultanIT** [comment]
hi Husein  ;)
Any solution for this problem , ihave the same !!!
best regards..

**Comment by buffermet** [comment]
Hi @Hossein228.

Your screenshot does not show any errors.

I believe you might have mistakenly interpreted the `not running` text (in red) as an error, but this simply means that you have not launched the module yet.

**Comment by ConsultanIT** [comment]
hi @buffermet 
i have the same error screen as housein ,

192.168.1.0/24 > 192.168.1.13  » bettercap ui
192.168.1.0/24 > 192.168.1.13  » [13:29:18] [sys.log] [err] unknown or invalid syntax "bettercap ui", type help for the help menu.
192.168.1.0/24 > 192.168.1.13  » ui.update
192.168.1.0/24 > 192.168.1.13  » [13:29:23] [sys.log] [err] unknown or invalid syntax "ui.update", type help for the help menu.
192.168.1.0/24 > 192.168.1.13  » set ui.update /usr/share/bettercap/
192.168.1.0/24 > 192.168.1.13  » ui.update
192.168.1.0/24 > 192.168.1.13  » [13:33:43] [sys.log] [err] unknown or invalid syntax "ui.update", type help for the help menu.
192.168.1.0/24 > 192.168.1.13  » help ui

ui (not running): A module to manage bettercap's UI. Disabled in Kali: use apt install bettercap-ui to install and/or update ui.

**Comment by buffermet** [comment]
Hi @ConsultanIT 

I am unable to reproduce your issue. When I run `ui.update`, the module successfully launches and updates my UI.

Are you sure that you are using the latest version of bettercap?

**Comment by ConsultanIT** [comment]
hi @buffermet 

thanks for you re response  👍 
Yes  its a latest version bettercap v2.28  in >> Kali 2020.3

up not able to launch bettercap UI !!

best regards

**Comment by buffermet** [comment]
@ConsultanIT 

That's odd. We're getting very different output:

<img width="663" alt="Screen Shot 2020-09-26 at 11 18 52 pm" src="https://user-images.githubusercontent.com/29265684/94341689-b6d82600-004e-11eb-8826-21de46ac9561.png">

What output do you get when you do `sudo bettercap -version` ?

You may also want to try `ui.update on`, but something is still telling me that you are not launching the latest version of bettercap. Perhaps you have multiple installations on your system?

**Comment by ConsultanIT** [comment]
bettercap v2.28 (built for linux amd64 with go1.14.4)

![image](https://user-images.githubusercontent.com/34819160/94341766-f88faf00-0003-11eb-9815-e815357d14dd.png)

![image](https://user-images.githubusercontent.com/34819160/94341799-502e1a80-0004-11eb-9169-c220e3792a67.png)

**Comment by buffermet** [comment]
@ConsultanIT 

Your apache server should not interfere with bettercap's `ui.update` module.

I am honestly not sure why you are not getting the expected output.

What if you first try to update bettercap and its dependencies?

`go get -u github.com/bettercap/bettercap`

**Comment by ConsultanIT** [comment]
![image](https://user-images.githubusercontent.com/34819160/94342317-3c84b300-0008-11eb-921b-ade494e1bbe2.png)
What if you first try to update bettercap and its dependencies?

**Comment by buffermet** [comment]
@Hossein228 @ConsultanIT 

I'll need more info from one of you about your setup. Can you please provide all the information that was requested in the GitHub issue template?

**Comment by OptX** [comment]
@buffermet 
I am running into the same problems on my pi 4b with the 'Kali Linux RaspberryPi 2 (v1.2), 3 and 4 (64-Bit) 2020.3a' image.
Also get the same output in bettercap as ConsultanIT. 
Same version [bettercap v2.28 (built for linux amd64 with go1.14.4)]
'apt-get install bettercap-ui' did not output any error during install, but also did nothing to help fixing the ui problem.

**Comment by OptX** [comment]
@buffermet @ConsultanIT 
I would say this is (was) a kali pi problem.
I followed all the steps how to install bettercap manualy and now everything works.
Bettercap ui up and running on my Pi 4b with latest kali img.

**Comment by r1ckyr4y** [comment]
Any solution to this problem? I am running into it as well.

**Comment by lalit3011agarwal** [comment]
Same Problem here aswell!
![image](https://user-images.githubusercontent.com/70253887/122639163-dc91e780-d115-11eb-8ab2-49c1203428aa.png)
