### ISSUE TITLE
Caplet http-ui, bind address already in use

### ISSUE THREAD

**Issue by CyberFlo2005** [bettercap/ui#39]
I hope this is the right place for this issue,
Im using linux mint (amd64) and trying to start bettercap.
If i'm trying to start bettercap with ~$ sudo bettercap -caplet http-ui,
im getting following error:

```
bettercap v2.28 (built for linux amd64 with go1.14.4) [type 'help' for a list of commands]

192.168.10.0/24 > 192.168.10.28  » [23:51:51] [sys.log] [inf] http.server starting on http://127.0.0.1:80
panic: listen tcp 127.0.0.1:8081: bind: address already in use

goroutine 27 [running]:
github.com/bettercap/bettercap/modules/api_rest.(*RestAPI).Start.func1()
	/build/bettercap-F2qCew/bettercap-2.28/modules/api_rest/api_rest.go:288 +0x309
created by github.com/bettercap/bettercap/session.(*SessionModule).SetRunning
	/build/bettercap-F2qCew/bettercap-2.28/session/module.go:281 x1ba
```
I also tried running bettercap from docker, otherprecompiled binaries and self compiled.
I tried running the https-ui caplet, which worked, but I got this error while trying to log in: cant cnnect to api 
I found some similar issues in WSL (windows subsystem for linux) but I didnt found this issue with linux yet.
Any solution for this?

**Comment by buffermet** [comment]
Hey, the error is pretty clear there: `address already in use `.

You are already serving on port 8081, you will have to terminate that first, or use a different port.
