### ISSUE TITLE
kishan

### ISSUE THREAD

**Issue by kishan-shanthakumar** [bettercap/ui#59]
![image](https://user-images.githubusercontent.com/69047931/121821186-0d58c380-ccb5-11eb-8c7d-38dc46b3cf4e.png)
When I try to bettercap, it gets stuck at the above image with no prompt and any command I enter, I think, is being ignored. I am a total beginner. Any help is appreciated.
This is run on Ubuntu 20.04.
I am trying to do this on wifi.

**Comment by buffermet** [comment]
You are running the legacy version of bettercap which is no longer supported.
