### ISSUE TITLE
Doesn't use iu panel 

### ISSUE THREAD

**Issue by Efemecit123567** [bettercap/ui#81]
I open iu panel but cant sign in bettercap forward http://127.0.0.1/#/events always.
![bettercap_issue](https://user-images.githubusercontent.com/53465778/163555652-045a1454-4d3d-4281-a2fa-4cd3ff399656.PNG)
![bettercap issue](https://user-images.githubusercontent.com/53465778/163555654-9ec3bf33-9938-4b94-893f-64ba44842980.PNG)

**Comment by berkkendirlioglu** [comment]
I have a same problem, Read the all documentation the bettercap but i can't fixed this problem. I try `ui.update` and `bettercap -eval "caplets.update; ui.update; q"` but not working.

### Environment

- Bettercap: v2.32.0
- UI: v1.3.0
- OS: Kali Linux 2022.1 amd64
- Browser: Firefox and tried clear cache 
- Command line: `bettercap -caplet http-ui`
- http-ui locate: /usr/local/share/bettercap/caplets/
- UI locate: /usr/local/share/bettercap/

**http-ui file:**
`# api listening on http://127.0.0.1:8081/ and ui to http://127.0.0.1
set api.rest.address 127.0.0.1 **// try this change to 0.0.0.0**
set api.rest.port 8081
set http.server.address 127.0.0.1 **// try this change to 0.0.0.0**
set http.server.port 80
# default installation path of the ui
set http.server.path /usr/local/share/bettercap/ui

# !!! CHANGE THESE !!!
set api.rest.username **_change_**
set api.rest.password **_change_**

# go!
api.rest on
http.server on`

 # Result:
![ui](https://user-images.githubusercontent.com/71317893/165658497-f7e83de0-f047-4678-82e6-bbabc3d6fd9a.png)

**Comment by uDust** [comment]
same here!
![Screenshot_2022-06-10_16_07_28](https://user-images.githubusercontent.com/97496829/173152841-cd737677-ac62-4326-a023-909758fd4c29.png)

**Comment by Hector6704** [comment]
same problem here

**Comment by digitalirony** [comment]
super same

**Comment by veerendra2** [comment]
+1

**Comment by rootbesi** [comment]
Hi Team,

How about this bug?also faced same issue,hope got reply and solutions for this..need to use to do a demo for awareness

**Comment by konsumer** [comment]
Same issue. The problem seems to be in the kali package. I didn't have the problem running release-build, like this:

Find the release for your machine [here](https://github.com/bettercap/bettercap/releases/tag/v2.31.1)

```
wget https://github.com/bettercap/bettercap/releases/download/v2.31.1/bettercap_linux_aarch64_v2.31.1.zip
unzip bettercap_*.zip
sudo ./bettercap

caplets.update
ui.update
https-ui enable
```

**Comment by undermuz** [comment]
this error is due to the session. it does not contain information on the key of some module
in my case, it happens due to the lack of a ble module

https://github.com/bettercap/ui/blob/93cf25268ff70f8ee30dafd11dafeb19fc973983/src/app/components/ble-table/ble-table.component.ts#L89

![image](https://user-images.githubusercontent.com/6875507/237055055-b851654a-3097-4e63-9490-90e7f52fa3ea.png)

**Comment by evilsocket** [comment]
the problem is in the kali package, not in the UI or bettercap itself
