### ISSUE TITLE
ui - wifi wlan0 although selected was not working, had to re set it

### ISSUE THREAD

**Issue by megahz** [bettercap/ui#9]
*Description of the bug or feature request*

### Environment

Please provide:

* Bettercap version you are using ( `bettercap -version` ).
2.21.1
* OS version and architecture you are using.
debian linux
* Go version if building from sources.
1.11
* Command line arguments you are using.
starting the ui 
* Caplet code you are using or the interactive session commands.
http-ui

### Steps to Reproduce

1. open ui,, login
2. go to wifi module, saw that the wlan0 is selected
2. go to advanced, set the wifi.recon on
3. error: eth0 interface cannot be used .
4. go to the wifi module, rechoose the wlan0 from the dropdown
5. go to advanced set again the wifi.recon on, no issue

it seems like although initially the wlan0 appeared, it was not working and i had to reselect it.

**Comment by evilsocket** [comment]
instead of going to the advanced tab, just use the "play" button in the wifi tab, that will select the interface and start the module ;)
